### ISSUE TITLE
Request failed with status code 500 - Error report for exile-diary 1.1.0

### ISSUE THREAD

**Issue by Mithgroth** [Qt-dev/exile-diary#191]
Error:
```
AxiosError: Request failed with status code 500
    at settle (X:\3rd Party\Path of Exile\Exile Diary Reborn\resources\app.asar\node_modules\axios\dist\node\axios.cjs:1909:12)
    at IncomingMessage.handleStreamEnd (X:\3rd Party\Path of Exile\Exile Diary Reborn\resources\app.asar\node_modules\axios\dist\node\axios.cjs:2989:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
OS: Windows NT 10.0.22621
App: exile-diary 1.1.0

**Comment by zekeflynn** [comment]
![image](https://github.com/Qt-dev/exile-diary/assets/33818126/58e79b5a-8790-4492-880f-31212e9d9f05)

**Comment by goronix** [comment]
Should be fixed; they had Cloudflare up for a few hours.

**Comment by zekeflynn** [comment]
> Should be fixed; they had Cloudflare up for a few hours.

Nope, still happening to me.

**Comment by Jbelles** [comment]
Can confirm exact issue still occurs

**Comment by willlowther** [comment]
Also confirming that this issue still happens every time for me

**Comment by mrmason** [comment]
same here!

**Comment by ArawnDA** [comment]
Same issue today

**Comment by Qt-dev** [comment]
Found the issue and added a temporary fix. Please retry, you guys should be good to go now :)

**Comment by goronix** [comment]
Temp fix seems to have worked; thank you!!

**Comment by willlowther** [comment]
Unfortunately still having the same issue

**Comment by ArawnDA** [comment]
Success!  Thank you

**Comment by Qt-dev** [comment]
@willlowther : Is it still happening to you now?

**Comment by Qt-dev** [comment]
Closing it, I believe this is gone now
